---
# THIS TASK IS CONFIGURING THE SWITCHPORT WITH THE DESIRED VLANS

- name: CONFIGURE ACCESS PORT
  ios_l2_interfaces:
    config:
    - name: "{{ item.name }}"
      mode: "{{ item.mode }}"
      access:
        vlan: "{{ item.vlan_id }}"
  loop: "{{ vlans | selectattr('mode', 'equalto', 'access') }}"
  when: 
    - "'ios_switches' in group_names"
      
- name: CONFIGURE TRUNK PORT
  ios_l2_interfaces:
    config:
      trunk:
        allowed_vlans: "{{ item.allowed_vlans }}"
        native_vlan: "{{ item.native_vlan }}"
        encapsulation: "{{ item.encapsulation }}"
    state: merged
  loop: "{{ vlans | selectattr('mode', 'equalto', 'trunk')}}"
  when: 
    - "'ios_switches' in group_names"
 
- name: CHANGE L2 INTERFACE STATUS 
  ios_interfaces:
    config:
    - name: "{{ item.name }}"
      description: "{{ item.description }}"
      enabled: "{{ item.enabled }}"
  loop: "{{ interfaces }}"
  when: 
    - "'ios_switches' in group_names"

