---
- name: Using condetional
  hosts: ios_devices
  gather_facts: no
  tasks:

    - name: Run for the edge nodes only
      debug:
        msg: "Router name is {{ hostname }}"
      when: "'edge' is in group_names"
    
    - name: Run for core only
      debug: 
        msg: "{{ hostname }} is running {{ os }}"
      when: 
        - inventory_hostname == 'core_01'