---
- name: configure envirnonment interfaces
  gather_facts: yes
  connection: network_cli
  hosts: ios_devices
  tasks:
    - name: change interface status for routers
      ios_interfaces:
        config:
        - name: "{{ item.name }}"
          description: "{{ item.description }}"
          enabled: "{{ item.enabled }}"
      loop: "{{ interfaces }}"
      when: "interfaces is defined"

    - name: change interface IP     
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "{{ item.name }}"
          ipv4: 
          - address: "{{ item.ipv4 }}" # THE ADDRESS IS WRITTEN IN CIDR NOTATION
      loop: "{{ interfaces }}"
      when: "interfaces is defined"

    - name: configure access port
      ios_l2_interfaces:
        config:
        - name: "{{ item.name }}"
          mode: "{{ item.mode }}"
          access:
            vlan: "{{ item.vlan_id }}"
      register: vlan_output
      loop: "{{ vlans | selectattr('mode', 'equalto', 'access') }}"
      when: "'ios_switches' in group_names"

    - name: configure trunk port
      ios_l2_interfaces:
        config:
          trunk:
            allowed_vlans: "{{ item.allowed_vlans }}" # A LIST OF VLANS SEPERATED BY A COMMA
            native_vlan: "{{ item.native_vlan }}" 
            encapsulation: "{{ item.encapsulation }}"
        state: merged
      loop: "{{ vlans | selectattr('mode', 'equalto', 'trunk')}}"
      when: "'ios_switches' in group_names"

    - name: configre routing
      cisco.ios.ios_static_routes:
        config:
        - address_families:
          - afi: "{{ item.address_family }}" # THIS IS THE IP VERSION 4/6 (IPV4/IPV6)
            routes: 
              - dest: "{{ item.destination }}" 
                next_hops:
                  - forward_router_address: "{{ item.next_hops }}"
      #              name: "{{ item.name }}" #Not supported with IOS XE
     #               when: ansible_net_image == "IOS XR"
      loop: "{{ routes.static }}"
      when: "'ios_routers' in group_names and routes is defined"

    - name: print ansible image  
      debug:
        msg: "{{ ansible_net_image }}"

    - name: Display VLANS
      debug:
        #msg: "The first device {{ inventory_hostname }} has the following vlans {{ item.stdout }}"
        #msg: "{{ vlan_output }}"
      #loop: "{{ vlan_output | map(attribute = 'results') | list | selectattr('item, 'equalto' ')}}"
      when: "'switches' in group_names"
