---
- name: configure envirnonment interfaces
  gather_facts: no
  connection: network_cli
  hosts: ios_devices
  tasks:
    - name: change interface status for routers
      ios_interfaces:
        config:
        - name: {{ item.name }}
          description: {{ item.description }}
          enabled: {{ item.enabled }}
      loop: "{{ interfaces }}"

    - name: change interface IP     
      cisco.ios.ios_l3_interfaces:
        config:
          - name: {{ item.name }}
            ipv4: 
            - address: {{ item.ipv4.address }}
      loop: " {{ interfaces }}"

    - name: configure access port
      ios_l2_interfaces:
        config:
        - name: {{ item.name }}
          mode: {{ item.mode }}
          access:
           vlan: {{ item.vlan_id }}
      loop: {{ vlans | selectattr('mode', 'equalto', 'access') }}
      when: "'ios_switches' in group_names"

    - name: configure trunk port
      ios_l2_interfaces:
        config:
          trunk:
            allowed_vlans: {{ item.allowed_vlans }}
            native_vlan: {{ item.native_vlan }}
            encapsulation: {{ item.encapsulation }}
        state: merged
      loop: {{ vlans | selectattr('mode', 'equalto', 'trunk')}}
      when: "'ios_switches' in group_names"

    - name: configre routing
      ios_static_routes:
        config:
        - address_family:
          - afi: {{ item.address_family }}
            routes: 
              - dst: {{ item.destination }}
                next_hops:
                - forward_router_address: {{ item.next_hops }}
                  name: {{ item.name }}
      loop: {{ routes.static }}
      when: "'ios_routers' in group_names"
