---

- name: configure envirnonment interfaces
  gather_facts: no
  connection: network_cli
  hosts: ios_devices
  tasks:

    - name: configre edge_01 wan interfaces
      ios_interfaces:
        config:
        - name: ethernet0/0
          description: "WAN Primary IF"
          enabled: yes
      cisco.ios.ios_l3_interfaces:
        config:
          - name: ethernet0/0
            ipv4: 
            - address: 10.0.0.2/24
      when:  inventory_hostname == "edge_01"
