---
- name: Ansible loop over a list
  hosts: ios_devices
  gather_facts: no
  tasks:

    - name: Loop over SNMP servers
      debug:
        msg: "Router {{ inventory_hostname }} with SNMP server {{ item }} "
      loop: "{{ snmp_servers }}"
    
    - name: loop over users
      debug:
        msg: "router {{ inventory_hostname }} with user {{ item.key }} password {{ item.value }}"
      with_dict: 
        - "{{ users }}"
