---
# handlers file for ios_l2_if

#- name: "IFstatus {{ item }}"
  #ios_interfaces:
  #  config:
  #    - name: "{{ item.name }}"
  #      description: "{{ item.description }}"
  #      enabled: "{{ item.enabled }}"
  #loop: "{{ interfaces }}"
  #when: 
  #  - "interfaces is defined"
