- name: Play
  hosts: localhost
  tasks:
    - name: iterate
      debug:
         msg: "{{ hostvars[item].role }}"#"{{ item }}:{{ hostvars[item].role }}"
      with_items:
        - "{{ groups['all'] }}"