---
- name: Populate NetBox DataBase
  hosts: all #localhost
  gather_facts: no
  vars:
    #ansible_python_interpreter: /usr/bin/python3
    #ansible_connection: local
    netbox_state: present
  
  roles:
    - build_netbox_db
  