- name: "Test Netbox modules"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create device within Netbox with only required information
      netbox_device:
        netbox_url: http://192.168.12.128
        netbox_token: b9b782a631b321b8a1a22f96ef2a1fc341b7f218
        data:
          name: Test Device
          device_type: C9410R
          device_role: Core Switch
          site: Main
        state: present