---
ansible_host: 192.168.1.202
site: EA-DC
role: CORE
model: CSR1000v

interfaces:
  - name: vlan 1
    description: "EDGE_RTR IF"
    ipv4: 192.168.100.3/24
    state: merged
    enabled: true

  - name: vlan 100
    description: "IT IF"
    ipv4: 172.31.1.1/24
    state: merged
    enabled: true

  - name: vlan 101
    description: "SALES IF"
    ipv4: 172.30.1.1/24
    state: merged
    enabled: true

vlans:
  - name: ethernet 0/0
    mode: access
    vlan_id: 1

  - name: ethernet 0/1
    mode: access
    vlan_id: 1
  
  - name: ethernet 2/0
    mode: access
    vlan_id: 100

  - name: ethernet 2/1
    mode: access
    vlan_id: 101
  
